name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-33" \
                     "build-tools;33.0.2"

      - name: Fix Gradle Memory
        run: |
          echo "org.gradle.jvmargs=-Xmx4096m" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "org.gradle.workers.max=2" >> gradle.properties

      - name: Clean
        run: ./gradlew clean

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
