name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Build Tools
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-33" \
                     "build-tools;33.0.2"

      - name: Fix AAPT2 Crash (IMPORTANT)
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m" >> gradle.properties
          echo "org.gradle.daemon=false" >> gradle.properties
          echo "org.gradle.workers.max=1" >> gradle.properties

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
